From e59f73e5d2441079f97e999fede37ac128d19346 Mon Sep 17 00:00:00 2001
From: Paper <paper@tilde.institute>
Date: Thu, 1 Apr 2021 16:59:56 +0200
Subject: [PATCH] f

---
 Makefile | 29 -----------------------------
 1 file changed, 29 deletions(-)

diff --git a/Makefile b/Makefile
index 2d9cb79..226f345 100644
--- a/Makefile
+++ b/Makefile
@@ -93,62 +93,35 @@ DOC_ID                 := $(ARTIFACT_ID)-doc-$(LSP_VERSION)
 
 default: all
 
-all: export CFLAGS          += -O2 -DLSP_NO_EXPERIMENTAL
-all: export CXXFLAGS        += -O2 -DLSP_NO_EXPERIMENTAL
-all: export EXE_FLAGS       += -pie -fPIE
 all: compile
 
-experimental: export CFLAGS += -O2
-experimental: export CXXFLAGS += -O2
 experimental: compile
 
-trace: export CFLAGS        += -O2 -DLSP_TRACE -g3 -fstack-protector
-trace: export CXXFLAGS      += -O2 -DLSP_TRACE -g3 -fstack-protector
 trace: export EXE_FLAGS     += -g3
 trace: compile
 
 test: OBJDIR                 = $(TESTDIR)
-test: export CFLAGS         += -O2 -DLSP_TESTING -DLSP_TRACE -g3 -fstack-protector
-test: export CXXFLAGS       += -O2 -DLSP_TESTING -DLSP_TRACE -g3 -fstack-protector
-test: export EXE_TEST_FLAGS += -g3
 test: export MAKE_OPTS      += LSP_TESTING=1
 test: export BUILD_MODULES   = jack
 test: test_compile
 
 testdebug: OBJDIR                 = $(TESTDIR)
-testdebug: export CFLAGS         += -O0 -DLSP_TESTING -DLSP_TRACE -g3 -fstack-protector
-testdebug: export CXXFLAGS       += -O0 -DLSP_TESTING -DLSP_TRACE -g3 -fstack-protector
-testdebug: export EXE_TEST_FLAGS += -g3
 testdebug: export MAKE_OPTS      += LSP_TESTING=1
 testdebug: export BUILD_MODULES   = jack
 testdebug: test_compile
 
 testprofile: OBJDIR                 = $(TESTDIR)
-testprofile: export CFLAGS         += -g -pg -O2 -DLSP_PROFILING -DLSP_TESTING -DLSP_TRACE -g3 -no-pie -fno-pie -fPIC -fstack-protector
-testprofile: export CXXFLAGS       += -g -pg -O2 -DLSP_PROFILING -DLSP_TESTING -DLSP_TRACE -g3 -no-pie -fno-pie -fPIC -fstack-protector
-testprofile: export EXE_TEST_FLAGS += -g -pg -O2 -g3 -no-pie -fno-pie -fPIC
 testprofile: export MAKE_OPTS      += LSP_TESTING=1
 testprofile: compile
 
-tracefile: export CFLAGS    += -DLSP_TRACEFILE
-tracefile: export CXXFLAGS  += -DLSP_TRACEFILE
 tracefile: trace
 
-debug: export CFLAGS        += -O2 -DLSP_DEBUG
-debug: export CXXFLAGS      += -O2 -DLSP_DEBUG
 debug: compile
 
-debugfile: export CFLAGS    += -DLSP_TRACEFILE
-debugfile: export CXXFLAGS  += -DLSP_TRACEFILE
 debugfile: debug
 
-gdb: export CFLAGS          += -O0 -g3 -DLSP_TRACE
-gdb: export CXXFLAGS        += -O0 -g3 -DLSP_TRACE
 gdb: compile
 
-profile: export CFLAGS      += -g -pg -DLSP_PROFILING -no-pie -fno-pie -fPIC
-profile: export CXXFLAGS    += -g -pg -DLSP_PROFILING -no-pie -fno-pie -fPIC
-profile: export EXE_FLAGS   += -g -pg -no-pie -fno-pie -fPIC
 profile: compile
 
 # Compilation and cleaning targets
@@ -268,8 +241,6 @@ install_doc: all
 	@cp -r $(OBJDIR)/html/* $(DESTDIR)$(DOC_PATH)/$(ARTIFACT_ID)
 
 # Release targets
-dbg_release: export CFLAGS        += -DLSP_TRACE -O2
-dbg_release: export CXXFLAGS      += -DLSP_TRACE -O2
 dbg_release: $(RELEASES)
 	@echo "Debug Release OK"
 
-- 
2.31.1

